name: jp_screen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  custom_sliding_segmented_control: ^1.8.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  flutter_sfsymbols: ^2.0.0
  flutter_svg: ^2.0.0
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/details/
    - assets/images/grafiken/
    - assets/icons/
    - assets/screens/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/grafiken/app_icon.png


